default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: PortalSolarDevTest_development
production:
  <<: *default
  database: PortalSolarDevTest_production
  username: PortalSolarDevTest
  password: <%= ENV['PORTALSOLARDEVTEST_DATABASE_PASSWORD'] %>
